"""Add trial_attributes table.

Revision ID: v4.1.0.a
Revises: v3.2.0.a
Create Date: 2024-09-13 10:49:15.556673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'v4.1.0.a'
down_revision = 'v3.2.0.a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create trial_attributes table.
    op.create_table('trial_attributes',
    sa.Column('trial_attribute_id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=512), nullable=True),
    sa.Column('value_json', sa.Text(), nullable=True),
    sa.Column('attr_type', sa.Enum('USER', 'SYSTEM', name='trialattrtype'), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], ),
    sa.PrimaryKeyConstraint('trial_attribute_id'),
    sa.UniqueConstraint('trial_id', 'key', 'attr_type')
    )
    op.create_table('trial_heartbeats',
    sa.Column('trial_heartbeat_id', sa.Integer(), nullable=False),
    sa.Column('trial_id', sa.Integer(), nullable=False),
    sa.Column('heartbeat', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['trials.trial_id'], ),
    sa.PrimaryKeyConstraint('trial_heartbeat_id'),
    sa.UniqueConstraint('trial_id')
    )

    # Data Migration (v4.1.0.b の中に記述)
    # ① trial_user_attributesモデルとtrial_system_attributesモデルのデータをtrial_attributesモデルにbulk insert。
    pass
    # ② trial_user_attributesモデルを削除
    op.drop_table('trial_user_attributes')
    # ③ trial_system_attributesモデルを削除
    op.drop_table('trial_system_attributes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop trial_attributes table.
    op.drop_table('trial_attributes')
    # op.create_table(...)
    # op.create_table(...)
    # ### end Alembic commands ###
