name: Publish distributions to PyPI or TestPyPI

# TestPyPI upload is scheduled in each weekday.
# PyPI upload is only activated if the release is published.
on:
  pull_request:
    types:
      - opened
    branches:
      - 'release-v3.1.1'

jobs:
  build-n-publish:
    name: Build and publish Python distributions to PyPI or TestPyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install twine
      run: |
        python -m pip install -U pip
        python -m pip install -U twine wheel

    - name: Change the version file for scheduled TestPyPI upload
      if: github.event_name == 'schedule'
      run: |
        OPTUNA_VERSION=$(cut -d '"' -f 2 optuna/version.py)
        DATE=`date +"%Y%m%d"`
        echo "__version__ = \"${OPTUNA_VERSION}${DATE}\"" > optuna/version.py

    - name: Build a tar ball
      run: |
        python setup.py sdist
        python setup.py bdist_wheel

    - name: Verify the distributions
      run: twine check dist/*

    - name: Verify the distributions
      run: twine check dist/*

    - uses: actions/upload-artifact@v3
      with:
        name: optuna-distribution-packages
        path: dist/*